### ISSUE TITLE
Can not see anything in the reference page

### ISSUE THREAD

**Issue by vortextemporum** [charlieroberts/Gibberish#28]
The page loads but there is no content in it

**Comment by charlieroberts** [comment]
Are you talking about the online reference? It's working for me... http://charlie-roberts.com/gibberish/docs/index.html

**Comment by vortextemporum** [comment]
Well, I think it was a temporary problem in my browser. Sorry for the bother!

**Comment by charlieroberts** [comment]
No worries! Glad it's working now.

**Comment by byokoo** [comment]
Hey, thanks for this wonderful project!

I can confirm that the reference page is blank if i follow the link on the playground page – https://www.charlie-roberts.com/gibberish/docs/index.html

That’s what led me here and gladly your link is working – http://charlie-roberts.com/gibberish/docs/index.html
